stages:
  - install
  - lint
  - test

Install:
  image: gcr.io/cloud-builders/npm:node-10.10.0
  stage: install
  script: npm install
  artifacts:
    name: $CI_PIPELINE_IID
    paths:
      - node_modules/
  only:
    refs:
      - merge_request

Lint:
  image: node
  stage: lint
  script:
    - npm i eslint
    - node_modules/eslint/bin/eslint.js .
  dependencies:
    - Install
  only:
    refs:
      - merge_request

Unit Test:
  image: gcr.io/cloud-builders/npm:node-10.10.0
  stage: test
  script: npm run coverage
  artifacts:
    name: $CI_PIPELINE_IID
    paths:
      - coverage/lcov.info
  dependencies:
    - Install
    - Decrypt
  only:
    refs:
      - merge_request
